#!/usr/bin/env bash
# Copyright 2025-2026 Bootstrap Academy
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Tests for issue #355: No silent truncation — per-bucket "N total, showing M,
# K more" accounting in HUMAN_REVIEW.md + a single finalize held-back log line.
# Pure-function tests only; NO AI models are invoked — every input is a
# handwritten JSON-Lines fixture (generated by a loop) and the code under test is
# pure jq + bash.
#
# Contract under test (from the issue acceptance criteria + research):
#
#   render_human_review_digest <run_id>
#     Each capped/curated section in HUMAN_REVIEW.md emits "N total, showing M,
#     K more" beneath its header (K = N - M, never omitted; "0 more" when K == 0).
#
#   human_review_heldback_summary <run_id>
#     PURE: prints (does not log) one reconciling line of the form
#       "Human review: <total> findings, <surfaced> surfaced, <held_back> held
#        back (critical/high +<h1>, medium-security +<h2>, remainder collapsed
#        across <T> theme(s))"
#     sourced from human_review_bucketize's FULL ordered lists. The numbers must
#     reconcile: surfaced + held_back == total. When nothing is held back it
#     reports "0 held back" / "no remainder" truthfully. Honors $LOG_BASE.
#
#   repolens.sh (finalize hook): emits the held-back line via log_info inside the
#   HUMAN_REVIEW-gated, non-fatal block. We assert the wiring statically (running
#   repolens.sh itself would invoke real agents — forbidden by the test rules).

# shellcheck disable=SC2030,SC2031 # Subshell-local test state is intentional.
set -uo pipefail
# shellcheck disable=SC2329  # helper functions are invoked indirectly

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CORE_LIB="$SCRIPT_DIR/lib/core.sh"
RISK_LIB="$SCRIPT_DIR/lib/risk.sh"
HUMAN_REVIEW_LIB="$SCRIPT_DIR/lib/human_review.sh"
REPOLENS_SH="$SCRIPT_DIR/repolens.sh"

PASS=0
FAIL=0
TOTAL=0

TMP_PARENT="$SCRIPT_DIR/logs/test-human-review-accounting"
mkdir -p "$TMP_PARENT"
TMPROOT="$(mktemp -d "$TMP_PARENT/run.XXXXXX")"

cleanup() {
  rm -rf "$TMPROOT"
  rmdir "$TMP_PARENT" 2>/dev/null || true
}
trap cleanup EXIT

pass_with() {
  PASS=$((PASS + 1))
  echo "  PASS: $1"
}

fail_with() {
  local desc="$1" detail="${2:-}"
  FAIL=$((FAIL + 1))
  echo "  FAIL: $desc"
  if [[ -n "$detail" ]]; then
    printf '    %s\n' "$detail"
  fi
}

assert_rc_zero() {
  local desc="$1" rc="$2"
  TOTAL=$((TOTAL + 1))
  if [[ "$rc" -eq 0 ]]; then pass_with "$desc"; else fail_with "$desc" "Expected rc 0, got $rc"; fi
}

# assert_contains <desc> <file> <fixed-string>
assert_contains() {
  local desc="$1" f="$2" needle="$3"
  TOTAL=$((TOTAL + 1))
  if [[ -f "$f" ]] && grep -qF -- "$needle" "$f"; then
    pass_with "$desc"
  else
    fail_with "$desc" "expected to find: $needle"
  fi
}

# assert_not_contains <desc> <file> <fixed-string>
assert_not_contains() {
  local desc="$1" f="$2" needle="$3"
  TOTAL=$((TOTAL + 1))
  if [[ -f "$f" ]] && grep -qF -- "$needle" "$f"; then
    fail_with "$desc" "did not expect to find: $needle"
  else
    pass_with "$desc"
  fi
}

# assert_str_contains <desc> <haystack> <fixed-string>
assert_str_contains() {
  local desc="$1" hay="$2" needle="$3"
  TOTAL=$((TOTAL + 1))
  if printf '%s' "$hay" | grep -qF -- "$needle"; then
    pass_with "$desc"
  else
    fail_with "$desc" "expected the summary to contain: $needle (got: $hay)"
  fi
}

# assert_eq <desc> <expected> <actual>
assert_eq() {
  local desc="$1" exp="$2" act="$3"
  TOTAL=$((TOTAL + 1))
  if [[ "$exp" == "$act" ]]; then
    pass_with "$desc"
  else
    fail_with "$desc" "expected '$exp', got '$act'"
  fi
}

assert_no_crash() {
  local desc="$1" errfile="$2"
  TOTAL=$((TOTAL + 1))
  if [[ -f "$errfile" ]] && grep -qiE 'unbound variable|syntax error|command not found' "$errfile"; then
    fail_with "$desc" "stderr indicates a crash: $(head -1 "$errfile")"
  else
    pass_with "$desc"
  fi
}

finish() {
  echo ""
  echo "Results: $PASS passed, $FAIL failed, $TOTAL total"
  if [[ "$FAIL" -gt 0 ]]; then
    exit 1
  fi
}

# setup_in <run_id> <jsonl-content> — fresh LOG_BASE, drop the fixture registry,
#   render the digest AND capture the held-back summary string. Sets:
#     RR_BASE, RR_OUT (rendered file), RR_ERR (stderr), RR_RC (render rc),
#     RR_SUMMARY (held-back line), RR_SUM_RC.
RUN_N=0
setup_in() {
  local run_id="$1" content="$2"
  RUN_N=$((RUN_N + 1))
  RR_BASE="$TMPROOT/lb-$RUN_N"
  mkdir -p "$RR_BASE/final"
  printf '%s' "$content" >"$RR_BASE/final/findings.jsonl"
  RR_OUT="$RR_BASE/final/HUMAN_REVIEW.md"
  RR_ERR="$TMPROOT/err-$RUN_N.txt"
  ( export LOG_BASE="$RR_BASE"; render_human_review_digest "$run_id" ) 2>"$RR_ERR"
  RR_RC=$?
  RR_SUMMARY="$( export LOG_BASE="$RR_BASE"; human_review_heldback_summary "$run_id" 2>>"$RR_ERR" )"
  RR_SUM_RC=$?
}

# gen_caps_fixture — 12 crit/high (bucket 1, cap 10) + 30 medium-security
#   (bucket 2, cap 25) + 3 test-gap (bucket 3, own section) + 2 external-dependency
#   (bucket 4, own section) + 4 remainder across 2 domains (bucket 5). Caps bite:
#   held1 = 2, held2 = 5; total 51, surfaced 40, held_back 11, themes 2.
gen_caps_fixture() {
  local i sev
  for i in $(seq 1 12); do
    sev="critical"; (( i % 2 == 0 )) && sev="high"
    printf '{"id":"ch-%02d","title":"crit-high finding %d","severity":"%s","type":"correctness","domain":"core","lens":"logic","status":"new","primary_location":"a.py:%d","confidence":null,"markdown_path":"","validation":{}}\n' "$i" "$i" "$sev" "$i"
  done
  for i in $(seq 1 30); do
    printf '{"id":"ms-%02d","title":"med-sec finding %d","severity":"medium","type":"security","domain":"security","lens":"injection","status":"new","primary_location":"b.py:%d","confidence":null,"markdown_path":"","validation":{}}\n' "$i" "$i" "$i"
  done
  for i in $(seq 1 3); do
    printf '{"id":"tg-%02d","title":"test gap %d","severity":"low","type":"test-gap","domain":"code-quality","lens":"tests","status":"new","primary_location":"t.py:%d","confidence":null,"markdown_path":"","validation":{}}\n' "$i" "$i" "$i"
  done
  for i in $(seq 1 2); do
    printf '{"id":"ed-%02d","title":"vuln dep %d","severity":"low","type":"external-dependency","domain":"deps","lens":"cve","status":"new","primary_location":"pkg.json:%d","confidence":null,"markdown_path":"","validation":{}}\n' "$i" "$i" "$i"
  done
  for i in $(seq 1 2); do
    printf '{"id":"rm-perf-%02d","title":"perf nit %d","severity":"low","type":"performance","domain":"perf","lens":"hot","status":"new","primary_location":"p.py:%d","confidence":null,"markdown_path":"","validation":{}}\n' "$i" "$i" "$i"
  done
  for i in $(seq 1 2); do
    printf '{"id":"rm-ui-%02d","title":"ui nit %d","severity":"low","type":"performance","domain":"ui","lens":"render","status":"new","primary_location":"u.py:%d","confidence":null,"markdown_path":"","validation":{}}\n' "$i" "$i" "$i"
  done
}

# gen_zero_fixture — 5 crit/high (<=10) + 10 medium-security (<=25), empty
#   remainder. Caps do NOT bite: held1 = 0, held2 = 0; total 15, surfaced 15,
#   held_back 0, no remainder.
gen_zero_fixture() {
  local i sev
  for i in $(seq 1 5); do
    sev="critical"; (( i % 2 == 0 )) && sev="high"
    printf '{"id":"zch-%02d","title":"crit-high %d","severity":"%s","type":"correctness","domain":"core","lens":"logic","status":"new","primary_location":"a.py:%d","confidence":null,"markdown_path":"","validation":{}}\n' "$i" "$i" "$sev" "$i"
  done
  for i in $(seq 1 10); do
    printf '{"id":"zms-%02d","title":"med-sec %d","severity":"medium","type":"security","domain":"security","lens":"injection","status":"new","primary_location":"b.py:%d","confidence":null,"markdown_path":"","validation":{}}\n' "$i" "$i" "$i"
  done
}

# --- Source the library. -----------------------------------------------------
# shellcheck source=/dev/null
[[ -f "$CORE_LIB" ]] && source "$CORE_LIB"
# shellcheck source=/dev/null
[[ -f "$RISK_LIB" ]] && source "$RISK_LIB"
if [[ -f "$HUMAN_REVIEW_LIB" ]]; then
  # shellcheck source=/dev/null
  source "$HUMAN_REVIEW_LIB"
fi

TOTAL=$((TOTAL + 1))
if declare -F render_human_review_digest >/dev/null 2>&1 \
   && declare -F human_review_heldback_summary >/dev/null 2>&1; then
  pass_with "render_human_review_digest + human_review_heldback_summary are defined"
else
  fail_with "render_human_review_digest + human_review_heldback_summary are defined" \
    "a function is missing — cannot run the rest of the suite"
  finish
fi

# ===========================================================================
# 1. Caps bite: per-section accounting strings + reconciling held-back line.
# ===========================================================================
CAPS_FIX="$(gen_caps_fixture)"
CAPS_TOTAL="$(printf '%s\n' "$CAPS_FIX" | grep -c .)"
setup_in "caps-run" "$CAPS_FIX"

assert_rc_zero  "caps fixture -> render rc 0" "$RR_RC"
assert_rc_zero  "caps fixture -> summary rc 0" "$RR_SUM_RC"
assert_no_crash "caps fixture does not crash" "$RR_ERR"
assert_eq "caps fixture has 51 findings" "51" "$CAPS_TOTAL"

# Per-section accounting (the no-silent-truncation strings).
assert_contains "Top Critical/High accounting: 12 total, showing 10, 2 more" \
  "$RR_OUT" "12 total, showing 10, 2 more"
assert_contains "Top Medium Security accounting: 30 total, showing 25, 5 more" \
  "$RR_OUT" "30 total, showing 25, 5 more"
# Uncapped own-sections render every finding -> "K more" is 0, truthfully.
assert_contains "Test & Quality accounting: 3 total, showing 3, 0 more" \
  "$RR_OUT" "3 total, showing 3, 0 more"
assert_contains "Not Actionable accounting: 2 total, showing 2, 0 more" \
  "$RR_OUT" "2 total, showing 2, 0 more"
# Accounting strings are integers only — no literal "null" leaks.
assert_not_contains "no literal 'null' in the accounting digest" "$RR_OUT" "null"

# Held-back summary line: exact reconciling content.
assert_str_contains "summary reports total findings"   "$RR_SUMMARY" "51 findings"
assert_str_contains "summary reports surfaced count"   "$RR_SUMMARY" "40 surfaced"
assert_str_contains "summary reports held-back count"  "$RR_SUMMARY" "11 held back"
assert_str_contains "summary reports critical/high surplus" "$RR_SUMMARY" "critical/high +2"
assert_str_contains "summary reports medium-security surplus" "$RR_SUMMARY" "medium-security +5"
assert_str_contains "summary reports remainder themes" "$RR_SUMMARY" "remainder collapsed across 2 theme(s)"
assert_str_contains "summary uses the [INFO]-loggable 'Human review:' prefix" \
  "$RR_SUMMARY" "Human review:"

# Reconciliation AC: surfaced + held_back == total == fixture line count.
TOTAL=$((TOTAL + 1))
if [[ "$RR_SUMMARY" =~ ([0-9]+)\ findings,\ ([0-9]+)\ surfaced,\ ([0-9]+)\ held\ back ]]; then
  s_total="${BASH_REMATCH[1]}"; s_surf="${BASH_REMATCH[2]}"; s_held="${BASH_REMATCH[3]}"
  if [[ "$s_total" -eq "$CAPS_TOTAL" && $((s_surf + s_held)) -eq "$s_total" ]]; then
    pass_with "reconciliation: surfaced + held_back == total == fixture lines"
  else
    fail_with "reconciliation: surfaced + held_back == total == fixture lines" \
      "total=$s_total surfaced=$s_surf held=$s_held fixture=$CAPS_TOTAL"
  fi
else
  fail_with "reconciliation: surfaced + held_back == total == fixture lines" \
    "could not parse the summary numbers from: $RR_SUMMARY"
fi

# ===========================================================================
# 2. Nothing held back: accounting reads "0 more" / "0 held back" truthfully.
# ===========================================================================
ZERO_FIX="$(gen_zero_fixture)"
ZERO_TOTAL="$(printf '%s\n' "$ZERO_FIX" | grep -c .)"
setup_in "zero-run" "$ZERO_FIX"

assert_rc_zero "zero fixture -> render rc 0" "$RR_RC"
assert_rc_zero "zero fixture -> summary rc 0" "$RR_SUM_RC"
assert_eq "zero fixture has 15 findings" "15" "$ZERO_TOTAL"

assert_contains "Top Critical/High within cap: 5 total, showing 5, 0 more" \
  "$RR_OUT" "5 total, showing 5, 0 more"
assert_contains "Top Medium Security within cap: 10 total, showing 10, 0 more" \
  "$RR_OUT" "10 total, showing 10, 0 more"

assert_str_contains "zero summary reports 15 findings" "$RR_SUMMARY" "15 findings"
assert_str_contains "zero summary reports 15 surfaced" "$RR_SUMMARY" "15 surfaced"
assert_str_contains "zero summary reports 0 held back"  "$RR_SUMMARY" "0 held back"
assert_str_contains "zero summary reports no remainder" "$RR_SUMMARY" "no remainder"
assert_str_contains "zero summary surplus critical/high +0" "$RR_SUMMARY" "critical/high +0"
assert_str_contains "zero summary surplus medium-security +0" "$RR_SUMMARY" "medium-security +0"

TOTAL=$((TOTAL + 1))
if [[ "$RR_SUMMARY" =~ ([0-9]+)\ findings,\ ([0-9]+)\ surfaced,\ ([0-9]+)\ held\ back ]]; then
  z_total="${BASH_REMATCH[1]}"; z_surf="${BASH_REMATCH[2]}"; z_held="${BASH_REMATCH[3]}"
  if [[ "$z_held" -eq 0 && $((z_surf + z_held)) -eq "$z_total" && "$z_total" -eq "$ZERO_TOTAL" ]]; then
    pass_with "zero held-back reconciles (held==0, surfaced==total==fixture lines)"
  else
    fail_with "zero held-back reconciles" "total=$z_total surfaced=$z_surf held=$z_held"
  fi
else
  fail_with "zero held-back reconciles" "could not parse: $RR_SUMMARY"
fi

# ===========================================================================
# 3. Empty registry: digest still renders; summary reports all-zero truthfully.
# ===========================================================================
setup_in "empty-run" ""
assert_rc_zero "empty registry -> render rc 0" "$RR_RC"
assert_rc_zero "empty registry -> summary rc 0" "$RR_SUM_RC"
assert_no_crash "empty registry does not crash" "$RR_ERR"
assert_str_contains "empty summary: 0 findings, 0 surfaced, 0 held back" \
  "$RR_SUMMARY" "0 findings, 0 surfaced, 0 held back"
# Empty capped sections still show the truthful accounting line.
assert_contains "empty Top Critical/High accounting: 0 total, showing 0, 0 more" \
  "$RR_OUT" "0 total, showing 0, 0 more"

# ===========================================================================
# 4. Static wiring check: repolens.sh emits the held-back line via log_info,
#    inside the HUMAN_REVIEW-gated, non-fatal finalize block.
# ===========================================================================
if [[ -f "$REPOLENS_SH" ]]; then
  assert_contains "repolens.sh calls human_review_heldback_summary" \
    "$REPOLENS_SH" "human_review_heldback_summary"
  assert_contains "repolens.sh logs the held-back summary via log_info" \
    "$REPOLENS_SH" 'log_info "$(human_review_heldback_summary'
  # The held-back line lives inside the HUMAN_REVIEW-gated, non-fatal hook block.
  TOTAL=$((TOTAL + 1))
  hook_block="$(awk '/Human review digest \(non-fatal\)/{c=1} c{print} /^# --- Human-triage artifacts/{if(c) exit}' "$REPOLENS_SH")"
  if printf '%s' "$hook_block" | grep -q 'human_review_heldback_summary' \
     && printf '%s' "$hook_block" | grep -q 'HUMAN_REVIEW:-false' \
     && ! printf '%s' "$hook_block" | grep -qw 'die'; then
    pass_with "held-back line is inside the HUMAN_REVIEW-gated, non-fatal block"
  else
    fail_with "held-back line is inside the HUMAN_REVIEW-gated, non-fatal block" \
      "hook block: $hook_block"
  fi
else
  echo "  (skip) repolens.sh not found at $REPOLENS_SH — wiring assertions skipped"
fi

finish
